/*
Deployment script for PropertyRentalManagementDB

This code was generated by a tool.
Changes to this file may cause incorrect behavior and will be lost if
the code is regenerated.
*/

GO
SET ANSI_NULLS, ANSI_PADDING, ANSI_WARNINGS, ARITHABORT, CONCAT_NULL_YIELDS_NULL, QUOTED_IDENTIFIER ON;

SET NUMERIC_ROUNDABORT OFF;


GO
:setvar DatabaseName "PropertyRentalManagementDB"
:setvar DefaultFilePrefix "PropertyRentalManagementDB"
:setvar DefaultDataPath "C:\Users\Yagnik Jasoliya\AppData\Local\Microsoft\VisualStudio\SSDT\PropertyRentalManagementDB"
:setvar DefaultLogPath "C:\Users\Yagnik Jasoliya\AppData\Local\Microsoft\VisualStudio\SSDT\PropertyRentalManagementDB"

GO
:on error exit
GO
/*
Detect SQLCMD mode and disable script execution if SQLCMD mode is not supported.
To re-enable the script after enabling SQLCMD mode, execute the following:
SET NOEXEC OFF; 
*/
:setvar __IsSqlCmdEnabled "True"
GO
IF N'$(__IsSqlCmdEnabled)' NOT LIKE N'True'
    BEGIN
        PRINT N'SQLCMD mode must be enabled to successfully execute this script.';
        SET NOEXEC ON;
    END


GO
USE [$(DatabaseName)];


GO
IF EXISTS (SELECT 1
           FROM   [master].[dbo].[sysdatabases]
           WHERE  [name] = N'$(DatabaseName)')
    BEGIN
        ALTER DATABASE [$(DatabaseName)]
            SET ARITHABORT ON,
                CONCAT_NULL_YIELDS_NULL ON,
                CURSOR_DEFAULT LOCAL 
            WITH ROLLBACK IMMEDIATE;
    END


GO
IF EXISTS (SELECT 1
           FROM   [master].[dbo].[sysdatabases]
           WHERE  [name] = N'$(DatabaseName)')
    BEGIN
        ALTER DATABASE [$(DatabaseName)]
            SET PAGE_VERIFY NONE,
                DISABLE_BROKER 
            WITH ROLLBACK IMMEDIATE;
    END


GO
ALTER DATABASE [$(DatabaseName)]
    SET TARGET_RECOVERY_TIME = 0 SECONDS 
    WITH ROLLBACK IMMEDIATE;


GO
IF EXISTS (SELECT 1
           FROM   [master].[dbo].[sysdatabases]
           WHERE  [name] = N'$(DatabaseName)')
    BEGIN
        ALTER DATABASE [$(DatabaseName)]
            SET QUERY_STORE (CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 367)) 
            WITH ROLLBACK IMMEDIATE;
    END


GO
PRINT N'Creating [dbo].[Apartments]...';


GO
CREATE TABLE [dbo].[Apartments] (
    [Apt_id]      INT           IDENTITY (1, 1) NOT NULL,
    [Build_id]    INT           NOT NULL,
    [Tenant_id]   INT           NULL,
    [Manager_id]  INT           NOT NULL,
    [Owner_id]    INT           NOT NULL,
    [Description] VARCHAR (MAX) NOT NULL,
    PRIMARY KEY CLUSTERED ([Apt_id] ASC)
);


GO
PRINT N'Creating [dbo].[Appointments]...';


GO
CREATE TABLE [dbo].[Appointments] (
    [A_id]                INT      IDENTITY (1, 1) NOT NULL,
    [Apt_id]              INT      NOT NULL,
    [potential_tenent_id] INT      NOT NULL,
    [Time]                DATETIME NOT NULL,
    PRIMARY KEY CLUSTERED ([A_id] ASC)
);


GO
PRINT N'Creating [dbo].[Buildings]...';


GO
CREATE TABLE [dbo].[Buildings] (
    [Build_id]    INT           IDENTITY (1, 1) NOT NULL,
    [Description] VARCHAR (MAX) NULL,
    PRIMARY KEY CLUSTERED ([Build_id] ASC)
);


GO
PRINT N'Creating [dbo].[Messages]...';


GO
CREATE TABLE [dbo].[Messages] (
    [M_Id]        INT            IDENTITY (1, 1) NOT NULL,
    [From_person] INT            NOT NULL,
    [To_person]   INT            NOT NULL,
    [Msg_content] NVARCHAR (MAX) NOT NULL,
    [Created_at]  DATETIME       NOT NULL,
    PRIMARY KEY CLUSTERED ([M_Id] ASC)
);


GO
PRINT N'Creating [dbo].[Persons]...';


GO
CREATE TABLE [dbo].[Persons] (
    [P_id]      INT           IDENTITY (1, 1) NOT NULL,
    [FirstName] VARCHAR (255) NOT NULL,
    [LastName]  VARCHAR (255) NULL,
    [Phone]     VARCHAR (20)  NULL,
    [Email]     VARCHAR (255) NOT NULL,
    [Role]      VARCHAR (50)  NOT NULL,
    PRIMARY KEY CLUSTERED ([P_id] ASC)
);


GO
PRINT N'Creating [dbo].[Users]...';


GO
CREATE TABLE [dbo].[Users] (
    [Id]       INT           NOT NULL,
    [Password] VARCHAR (255) NOT NULL,
    PRIMARY KEY CLUSTERED ([Id] ASC)
);


GO
PRINT N'Creating [dbo].[FK_Appartments_Manager]...';


GO
ALTER TABLE [dbo].[Apartments] WITH NOCHECK
    ADD CONSTRAINT [FK_Appartments_Manager] FOREIGN KEY ([Manager_id]) REFERENCES [dbo].[Persons] ([P_id]);


GO
PRINT N'Creating [dbo].[FK_Appartments_Owner]...';


GO
ALTER TABLE [dbo].[Apartments] WITH NOCHECK
    ADD CONSTRAINT [FK_Appartments_Owner] FOREIGN KEY ([Owner_id]) REFERENCES [dbo].[Persons] ([P_id]);


GO
PRINT N'Creating [dbo].[FK_Appartments_Tenant]...';


GO
ALTER TABLE [dbo].[Apartments] WITH NOCHECK
    ADD CONSTRAINT [FK_Appartments_Tenant] FOREIGN KEY ([Tenant_id]) REFERENCES [dbo].[Persons] ([P_id]);


GO
PRINT N'Creating [dbo].[FK_Appartments_Buildings]...';


GO
ALTER TABLE [dbo].[Apartments] WITH NOCHECK
    ADD CONSTRAINT [FK_Appartments_Buildings] FOREIGN KEY ([Build_id]) REFERENCES [dbo].[Buildings] ([Build_id]);


GO
PRINT N'Creating [dbo].[FK_Appointments_Persons]...';


GO
ALTER TABLE [dbo].[Appointments] WITH NOCHECK
    ADD CONSTRAINT [FK_Appointments_Persons] FOREIGN KEY ([potential_tenent_id]) REFERENCES [dbo].[Persons] ([P_id]);


GO
PRINT N'Creating [dbo].[FK_Appointments_Appartments]...';


GO
ALTER TABLE [dbo].[Appointments] WITH NOCHECK
    ADD CONSTRAINT [FK_Appointments_Appartments] FOREIGN KEY ([Apt_id]) REFERENCES [dbo].[Apartments] ([Apt_id]);


GO
PRINT N'Creating [dbo].[FK_Massages_Persons]...';


GO
ALTER TABLE [dbo].[Messages] WITH NOCHECK
    ADD CONSTRAINT [FK_Massages_Persons] FOREIGN KEY ([From_person]) REFERENCES [dbo].[Persons] ([P_id]);


GO
PRINT N'Creating [dbo].[FK_Massages_Persons2]...';


GO
ALTER TABLE [dbo].[Messages] WITH NOCHECK
    ADD CONSTRAINT [FK_Massages_Persons2] FOREIGN KEY ([To_person]) REFERENCES [dbo].[Persons] ([P_id]);


GO
PRINT N'Creating [dbo].[FK_Users_Persons]...';


GO
ALTER TABLE [dbo].[Users] WITH NOCHECK
    ADD CONSTRAINT [FK_Users_Persons] FOREIGN KEY ([Id]) REFERENCES [dbo].[Persons] ([P_id]);


GO
PRINT N'Checking existing data against newly created constraints';


GO
USE [$(DatabaseName)];


GO
ALTER TABLE [dbo].[Apartments] WITH CHECK CHECK CONSTRAINT [FK_Appartments_Manager];

ALTER TABLE [dbo].[Apartments] WITH CHECK CHECK CONSTRAINT [FK_Appartments_Owner];

ALTER TABLE [dbo].[Apartments] WITH CHECK CHECK CONSTRAINT [FK_Appartments_Tenant];

ALTER TABLE [dbo].[Apartments] WITH CHECK CHECK CONSTRAINT [FK_Appartments_Buildings];

ALTER TABLE [dbo].[Appointments] WITH CHECK CHECK CONSTRAINT [FK_Appointments_Persons];

ALTER TABLE [dbo].[Appointments] WITH CHECK CHECK CONSTRAINT [FK_Appointments_Appartments];

ALTER TABLE [dbo].[Messages] WITH CHECK CHECK CONSTRAINT [FK_Massages_Persons];

ALTER TABLE [dbo].[Messages] WITH CHECK CHECK CONSTRAINT [FK_Massages_Persons2];

ALTER TABLE [dbo].[Users] WITH CHECK CHECK CONSTRAINT [FK_Users_Persons];


GO
PRINT N'Update complete.';


GO
