//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PropertyRentalManagement.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Appointment
    {
        public int A_id { get; set; }
        public int Apt_id { get; set; }
        public int potential_tenent_id { get; set; }
        [DataType(DataType.DateTime)]
        public System.DateTime Time { get; set; }
    
        public virtual Person Person { get; set; }
        public virtual Appartment Appartment { get; set; }
    }
}
